name: logger_view
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  xterm:
    git:
      url: https://github.com/TerminalStudio/xterm.dart
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
